In [96]:
import pandas as pd
import numpy as np
from sklearn.svm import SVR
import matplotlib.pyplot as plt
import pickle
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.model_selection import cross_validate
from sklearn.model_selection import cross_val_score 
from sklearn.tree import export_graphviz
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
#Import big frame


modelframe = pd.read_csv("cleaned145dist.csv") 


In [6]:
#modelframe.to_csv("cleaned145dist.csv") 

In [87]:
#Create Model
clf = SVR(verbose=1)

In [129]:
#Create subset of features
X= modelframe[['Holiday', 'distance','precipIntensity', 'temperature', 'humidity', 'seconds']][0:20000]

In [130]:
#Create subset of target
Y=modelframe[["duration"]][0:20000]

In [131]:
#Normalise columns

feat_scaler = StandardScaler()
tar_scaler = StandardScaler()

X[['Holiday', 'distance','precipIntensity', 'temperature', 'humidity', 'seconds']] = feat_scaler.fit_transform(X[['Holiday', 'distance','precipIntensity', 'temperature', 'humidity', 'seconds']])
Y[["duration"]] = tar_scaler.fit_transform(Y[["duration"]])

E:\Anaconda\envs\env\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
E:\Anaconda\envs\env\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)
E:\Anaconda\envs\env\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
E:\Anaconda\envs\env\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [132]:
clf.fit(X,Y)

E:\Anaconda\envs\env\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


[LibSVM]

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
  gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
  tol=0.001, verbose=1)

In [100]:
#pkl_filename = "scaledmodelfortesting.pkl"
#with open(pkl_filename, 'wb') as file:
    #pickle.dump(clf, file)

In [123]:
#T = modelframe[['Holiday', 'distance','precipIntensity', 'temperature', 'humidity', 'seconds']][0:10]

In [124]:
#T[['Holiday', 'distance','precipIntensity', 'temperature', 'humidity', 'seconds']] = feat_scaler.transform(T[['Holiday', 'distance','precipIntensity', 'temperature', 'humidity', 'seconds']])

In [125]:
#T

In [94]:
tar_scaler.inverse_transform(clf.predict(T))

array([62.12981965, 55.1609414 , 61.28267235, 46.03480596, 51.40767756,
       48.37349172, 41.23965388, 36.81639428, 38.5402603 , 43.87871433])

## Assessing Model

In [126]:
scoring_list = ["neg_mean_absolute_error","neg_mean_squared_error"]
scores = cross_validate(clf, X, Y, scoring=scoring_list, cv=5,return_train_score = True)
scores

E:\Anaconda\envs\env\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
E:\Anaconda\envs\env\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


[LibSVM]

E:\Anaconda\envs\env\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
E:\Anaconda\envs\env\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


[LibSVM]

E:\Anaconda\envs\env\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
E:\Anaconda\envs\env\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


[LibSVM]

E:\Anaconda\envs\env\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
E:\Anaconda\envs\env\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


[LibSVM]

E:\Anaconda\envs\env\lib\site-packages\sklearn\utils\validation.py:761: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
E:\Anaconda\envs\env\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


[LibSVM]

{'fit_time': array([30.34981012, 30.49841547, 29.5639298 , 30.41962552, 29.84117794]),
 'score_time': array([4.91886759, 5.24895835, 4.64855099, 4.7712369 , 4.72139049]),
 'test_neg_mean_absolute_error': array([-0.76357167, -0.25141543, -0.3697169 , -0.11323479, -0.1730251 ]),
 'train_neg_mean_absolute_error': array([-0.12695603, -0.12332626, -0.12270174, -0.12834028, -0.11945729]),
 'test_neg_mean_squared_error': array([-1.03759279, -1.31278203, -1.18777392, -0.09714016, -2.16511173]),
 'train_neg_mean_squared_error': array([-1.05821814, -0.83722506, -0.88930344, -1.09299992, -0.61367438])}

In [127]:
for i in scores:
    print(i + ":")
    print (tar_scaler.inverse_transform(scores[i]))

fit_time:
[9600.05182184 9646.6887295  9353.41851373 9621.96203105 9440.42746991]
score_time:
[1619.0434309  1722.6360182  1534.20980524 1572.71239987 1557.06907002]
test_neg_mean_absolute_error:
[-164.27998893   -3.54967985  -40.67630154   39.81563553   21.05160707]
train_neg_mean_absolute_error:
[35.50949039 36.64862472 36.84461803 35.07507154 37.86282345]
test_neg_mean_squared_error:
[-250.27620622 -336.63901468 -297.40764321   44.86662505 -604.12617061]
train_neg_mean_squared_error:
[-256.74907078 -187.39467717 -203.73846591 -267.66465912 -117.23762855]
